---
name: Katharine L. Leigh
date: NULL
profilepic: kat_pic.jpg
www: kleigh@bren.usb.edu
github: KatLeigh11
linkedin: katharine-leigh-4821759a
headcolor: 414141
docname: CV/Resume
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyverse)
library(splitstackshape)

```

```{r}

CSV <- read_csv("data_CV.csv") %>%
  janitor::clean_names() %>%
  mutate(section = as.factor(section),
         subsection = as.factor(subsection),
         subsubsection = as.factor(subsubsection),
         category = as.factor(category)) %>% 
  group_by(section, subsection, subsubsection)

CSV2 <- pivot_wider(CSV, names_from = category, values_from = content) %>% 
  select(-tuna, -entity, -title)



CSVtest <- detailed_entries(data = CSV2, what = what, why = why, when = when, where = where, with = with)

EDF_intern <- CSV2 %>% 
  filter(section == "experience",
         subsection == "edf",
         subsubsection == "intern")
EDF_intern

```

